version: "3.8"

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agriv-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AI_INFERENCE_API_URL=http://ai-inference:8000
    depends_on:
      ai-inference:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # AI Inference API Service
  ai-inference:
    build:
      context: ./ai_inference_api
      dockerfile: Dockerfile
    container_name: agriv-ai-inference
    ports:
      - "8000:8000"
    volumes:
      - ./ai_inference_api/models:/app/models:ro
    env_file:
      - ./ai_inference_api/.env
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Application
  frontend:
    build:
      context: ./agriv_ai
      dockerfile: Dockerfile
    container_name: agriv-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - ai-inference
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
    name: agriv-app-network
